### ISSUE TITLE
SDL2_IMAGE_LIBRARIES / SDL2_IMAGE_INCLUDE_DIRS woes

### ISSUE THREAD

**Issue by CHiPs44** [raspberrypi/pico-host-sdl#1]
On Ubuntu 22.04, I can't build my project with pico-host-sdl (it works fine without on a real RPi Pico / VGA demo board):

```
$ cmake -DPICO_PLATFORM=host -DPICO_SDK_PRE_LIST_DIRS=/home/xxxxxxxx/src/pico-host-sdl ..
PICO_SDK_PATH is /home/xxxxxxxx/src/pico-sdk
PICO platform is host.
Build type is Release
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES
  SDL2_IMAGE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/xxxxxxxx/src/pico-host-sdl/cmake/FindSDL2_image.cmake:91 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/xxxxxxxx/src/pico-host-sdl/CMakeLists.txt:19 (find_package)
```
I tried to modify CMakeList.txt using https://gitlab.com/aminosbh/sdl2-cmake-modules.git as git submodule, but I got an error about Threads... This works fine with another project.

I spent several hours digging around forums, documentations to no avail.

**Comment by kilograham** [comment]
Do you have  and `libsdl2-dev` and `libsdl2-image-dev` packages installed?

**Comment by CHiPs44** [comment]
Yes, I have another SDL project building on the same machine.

**Comment by CHiPs44** [comment]
Project I'd like to build with pico-host-sdl is example dir of <https://github.com/CHiPs44/hagl_pico_vgaboard> (develop branch).

Project that builds with SDL2 on the same machine is <https://github.com/CHiPs44/space-invaders-sdl2>.

**Comment by CHiPs44** [comment]
I think I found the error I made, as `cmake -DPICO_PLATFORM=host -DPICO_SDK_PRE_LIST_DIRS=/home/chips/src/pico-host-sdl ..` works if I launch it from an empty `build2` directory, for example.

I've know to figure out how to exclude SDK includes and functions with `#ifndef PICO_NO_HARDWARE` IIRC.

**Comment by CHiPs44** [comment]
My project compiles now, open a window then dumps core, it seems I still have work to do!

And I still don't know enough of cmake to like it ;-)

**Comment by CHiPs44** [comment]
(closing issue, thanks for your help)
